# .github/workflows/main.yml
name: Build and Deploy Documentation

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch

jobs:
  publish-docs:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Dotnet Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '4.8.x'

    - run: dotnet tool update -g docfx
    - run: docfx Documentation/docfx/docfx.json

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Documentation/docfx/_site
